server:
  port: 9090
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/electronic_store
    password: Vanya@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: true
  # file config
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
# image path config
user:
  profile:
    image:
      path: images/users/
category:
  image:
    path: images/category/
product:
  image:
    path: images/category/